package-lock.json
src/Pages/Home.jsx
src/Pages/LeaderBoard.jsx
src/components/Hero.jsx
src/components/Navbar.jsx
src/components/Q&A.jsx
src/components/Stat.jsx

fix: register button on home page, page content hidden under navbar

---

src/components/Projects.jsx

fix: Reduce Hover Reflection Time in 'Our Projects' Section

---

src/Pages/LeaderBoard.jsx

With the [PR ID 10 in Backend](https://github.com/clubgamma/club-gamma-backend/pull/10), this minor update ensures that 
- the Leaderboard never crashes, 
- all of the filter functionality can be applied in the same time. 
- one API endpoint can be used for all
- request response is more tolerant for wrong input

Simplified contributor fetch function

---

src/components/Projects.jsx

**Enhance ProjectCard to show button on mobile devices**
- Added conditional rendering for the button to ensure it is always visible on mobile devices.
closes #17

Fixed: Hover Functionality not Working on Mobile Devices.

---

src/Global.js
src/components/Stat.jsx

Stat Component fetches data dynamically from backend.
If there's any error while fetching, the component conditionally renders  "Something went wrong, try again after some time".
@jalaym825 
closes #12

Stat component now fetches data dynamically

---

README.md

Made the Readme.md file cooler and better

---

src/components/Navbar.jsx

Set Events in Responsive Navbar

---

src/App.jsx
src/Pages/Team.jsx
src/components/Navbar.jsx
src/components/TeamCard.jsx

Add Team Section

---

src/components/ContactUs.jsx

fixed social icon responsiveness on home page
#32

feat: contact us social icons responsiveness

---

package.json
src/App.jsx
src/Pages/LeaderBoard.jsx
src/Pages/PointSystem.jsx
src/components/ui/table.jsx
src/components/ui/tooltip.jsx
src/index.css

1**. Point-system page** added ( In leaderboard page button point added)
2. **removing scroll-bar** in whole project (changes in index.css )
Closes #11

Point-system page 

---

package.json
src/App.jsx

Added smooth scrolling with Lenis for improved user experience

Added smooth scrolling

---

src/components/Projects.jsx

Now when you click anywhere on the project card It will redirect you to that reposritory

Click anywhere on projects card that will redirect to the github repo.

---

src/App.jsx
src/Pages/Contributors.jsx
src/components/Projects.jsx

updated Project contributer section

---

src/Pages/Profile.jsx

Open GitHub Page When PR Card is Clicked

---

src/components/Stat.jsx

Fixed Margin in stats in home page

Added Margin in stats

---

src/components/Projects.jsx
src/components/Stat.jsx

* Made the projects section responsive
* The projects component was breaking for medium scale devices

Made Projects Responsive

---

src/Pages/Profile.jsx
src/components/SyncPRs.jsx

add Sync Pr button in the profile page so when user is logged in then it show and the make API call "/api/users/sync-prs"

Add UI for syncing PRs

---

src/components/Projects.jsx

* Added filtering and categories in project component
* Better UX

Filtering and Categories in Projects

---

src/components/Navbar.jsx
src/components/Projects.jsx

* Improved the user dropdown button in navbar
* The button was not matching with the theme

Improved User Button/Dropdown

---

src/Pages/Home.jsx
src/components/Dock.jsx
src/components/Footer.jsx

Change footer of hf24 page

---

package.json
src/Pages/Home.jsx
src/components/Navbar.jsx
src/components/ui/scroll-area.jsx

About in home page

---

package.json
src/components/Navbar.jsx
src/components/ui/scroll-area.jsx

Improved Sidebar

---

src/App.jsx
src/components/Dock.jsx
src/components/Footer.jsx
src/components/Navbar.jsx
src/components/ProgressLevel.jsx

* Fixed interaction of sidebar with dock
* Made Profile page (Progress) responsive
* Added href to location of Charusat in footer

Made Sidebar and Profile Page Responsive

---

src/Pages/Profile.jsx

Made PRs Scrollable

---

src/Pages/Profile.jsx

Made the width of PRs responsive

---

src/Pages/Events.jsx
src/Pages/Profile.jsx

* Before
* After
* Before
* After

Improved Events Section and PRs Section

---

src/Pages/Profile.jsx
src/components/ProjectContributions.jsx

https://github.com/clubgamma/club-gamma-backend/pull/29

implement UI for project wise contribution

---

src/Pages/Events.jsx

Fixed Dates going to Second line for bigger titles

---

src/components/EventCard.jsx

Improved event modal

---

package.json
src/Pages/Profile.jsx

Added level in PRs

---

src/Pages/Profile.jsx

Fixed Bug with Level and made it responsive

---

src/Pages/Profile.jsx
src/components/ProjectContributions.jsx

Fixed Level Bug and made Project Contributions responsive

---

src/Pages/Profile.jsx

Added Filter in PRs and Removed ScrollBar

---

src/Pages/Profile.jsx

Added  PRs Count Based On FilterPRs Count Based On FilterPRs Count Based On Filter...

PRs Count Based On Filter

---

src/Pages/Home.jsx

No Hover Animation
No Animation

Added hover animations in Home Page for better UX
